xds:
  xds:
    shards: 3                     # must match replicaCount
    domain: bladedancer.dynu.net  # change to your domain
    # domain: gm-envoy.moloko.apic-k8s.axwaytest.net  # change to your domain
    # useProxyProto: true # MUST be true if annotated with service.beta.kubernetes.io/aws-load-balancer-proxy-protocol

back:
  envoyss:
    replicaCount: 3 # must match shards
    strategy: |
      type: RollingUpdate
    image:
      tag: v1.13.0
      repository: envoyproxy/envoy
    # Local debugging
    #xdsService:
    #  address: 192.168.1.42
    #  port: 10000
    #args:
    #  - -l
    #  - debug
    #  - -c
    #  - /env-config/envoy.yaml

# front:
#   envoy:
#     service:
#       annotations:
#         external-dns.alpha.kubernetes.io/hostname: '*.gm-envoy.moloko.apic-k8s.axwaytest.net.'
#         service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Project=apicentral
#         service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
